version: '3.8'

services:
  frontend:
    image: frontendv2
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: environmenv2
    ports:
      - 8080:8080
    container_name: backend
    environment: 
      - REDIS_HOST = redis_server
      
  redis_server:
    image: redis
    container_name: redis_server
