version: '3.8'

services:
  frontend:
    image: frontendv2
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: environmentv2
    ports:
      - 8080:8080
    
    environment: 
      - REDIS_HOST = redis_server
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    container_name: backend
    depends_on:
      - db
      - redis_server
      
  redis_server:
    image: redis
    restart: unless-stopped
    container_name: redis_server
    
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    container_name: nginx
    
